import Head from "next/head";
import styles from "../styles/Home.module.css";
import PostCard from '../components/PostCard'
import "bootstrap/dist/css/bootstrap.css";
import PostWidject from "../components/PostWidject";
import { getPosts } from "../services/index";

export default function Home({ posts }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <>
     <div className={styles.main}>
        
          {posts.map((post) => (
            <PostCard
              post={post.node}
              key={post.title}
              excerpt={post.excerpt}
              featuredPhoto={post.featuredPhoto}
              datePublished={post.datePublished}
              slug={post.slug}
            />
          ))}
      
      </div>
      <div>
        <PostWidject />
      </div>    
</> 
     
    </div>
  );
}
export async function getStaticProps() {
  const posts = (await getPosts()) || [];
  return {
    props: {
      posts,
    },
  };
}
